// <auto-generated />
using System;
using ContractMonthlyClaimSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ContractMonthlyClaimSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117130810_InitialOracleCreate")]
    partial class InitialOracleCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.AcademicManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MANAGER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LAST_NAME");

                    b.HasKey("ManagerId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_MANAGERS_EMAIL");

                    b.ToTable("ACADEMIC_MANAGERS", (string)null);
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ClaimItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ITEM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLAIM_ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("HOURLY_RATE");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("HOURS_WORKED");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("WORK_DATE");

                    b.HasKey("ItemId");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("IX_CLAIM_ITEMS_CLAIM");

                    b.HasIndex("WorkDate")
                        .HasDatabaseName("IX_CLAIM_ITEMS_WORKDATE");

                    b.ToTable("CLAIM_ITEMS", (string)null);
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Lecturer", b =>
                {
                    b.Property<int>("LecturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LECTURER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LecturerId"));

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CONTRACT_END_DATE");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CONTRACT_START_DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("EMPLOYEE_NUMBER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("HOURLY_RATE");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("PHONE_NUMBER");

                    b.HasKey("LecturerId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_LECTURERS_EMAIL");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_LECTURERS_EMP_NUM");

                    b.ToTable("LECTURERS", (string)null);
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.MonthlyClaim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLAIM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<DateTime>("ClaimMonth")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLAIM_MONTH");

                    b.Property<DateTime?>("CoordinatorApprovalDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("COORDINATOR_APPROVAL_DATE");

                    b.Property<string>("CoordinatorComments")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("COORDINATOR_COMMENTS");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COORDINATOR_ID");

                    b.Property<DateTime?>("CoordinatorReviewDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("COORDINATOR_REVIEW_DATE");

                    b.Property<int>("LecturerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LECTURER_ID");

                    b.Property<DateTime?>("ManagerApprovalDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MANAGER_APPROVAL_DATE");

                    b.Property<string>("ManagerComments")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MANAGER_COMMENTS");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MANAGER_ID");

                    b.Property<DateTime?>("ManagerReviewDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MANAGER_REVIEW_DATE");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PAYMENT_DATE");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("SUBMISSION_DATE");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("TOTAL_AMOUNT");

                    b.Property<decimal>("TotalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(8,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("TOTAL_HOURS");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimMonth")
                        .HasDatabaseName("IX_MONTHLY_CLAIMS_MONTH");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("IX_MONTHLY_CLAIMS_COORDINATOR");

                    b.HasIndex("LecturerId")
                        .HasDatabaseName("IX_MONTHLY_CLAIMS_LECTURER");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("IX_MONTHLY_CLAIMS_MANAGER");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MONTHLY_CLAIMS_STATUS");

                    b.ToTable("MONTHLY_CLAIMS", (string)null);
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ProgrammeCoordinator", b =>
                {
                    b.Property<int>("CoordinatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COORDINATOR_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoordinatorId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DEPARTMENT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LAST_NAME");

                    b.HasKey("CoordinatorId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_COORDINATORS_EMAIL");

                    b.ToTable("PROGRAMME_COORDINATORS", (string)null);
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.SupportingDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DOCUMENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CLAIM_ID");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CONTENT_TYPE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int>("DocumentType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DOCUMENT_TYPE");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("BLOB")
                        .HasColumnName("FILE_DATA");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("FILE_NAME");

                    b.Property<long>("FileSize")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("FILE_SIZE");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ORIGINAL_FILE_NAME");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPLOAD_DATE");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClaimId")
                        .HasDatabaseName("IX_SUPPORTING_DOCS_CLAIM");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("IX_SUPPORTING_DOCS_TYPE");

                    b.ToTable("SUPPORTING_DOCUMENTS", (string)null);
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COORDINATOR_ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<int>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LAST_NAME");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LECTURER_ID");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("BOOLEAN");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MANAGER_ID");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_COORDINATOR")
                        .HasFilter("\"COORDINATOR_ID\" IS NOT NULL");

                    b.HasIndex("LecturerId")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_LECTURER")
                        .HasFilter("\"LECTURER_ID\" IS NOT NULL");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_MANAGER")
                        .HasFilter("\"MANAGER_ID\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.HasIndex("UserType")
                        .HasDatabaseName("IX_USERS_TYPE");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ROLE_CLAIMS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USER_CLAIMS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("USER_LOGINS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("USER_ROLES", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("USER_TOKENS", (string)null);
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ClaimItem", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.MonthlyClaim", "MonthlyClaim")
                        .WithMany("ClaimItems")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyClaim");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.MonthlyClaim", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.ProgrammeCoordinator", "Coordinator")
                        .WithMany("ApprovedClaims")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ContractMonthlyClaimSystem.Models.Lecturer", "Lecturer")
                        .WithMany("MonthlyClaims")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContractMonthlyClaimSystem.Models.AcademicManager", "Manager")
                        .WithMany("FinalApprovedClaims")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coordinator");

                    b.Navigation("Lecturer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.SupportingDocument", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.MonthlyClaim", "MonthlyClaim")
                        .WithMany("SupportingDocuments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyClaim");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.User", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.ProgrammeCoordinator", "Coordinator")
                        .WithOne("User")
                        .HasForeignKey("ContractMonthlyClaimSystem.Models.User", "CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ContractMonthlyClaimSystem.Models.Lecturer", "Lecturer")
                        .WithOne("User")
                        .HasForeignKey("ContractMonthlyClaimSystem.Models.User", "LecturerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ContractMonthlyClaimSystem.Models.AcademicManager", "Manager")
                        .WithOne("User")
                        .HasForeignKey("ContractMonthlyClaimSystem.Models.User", "ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coordinator");

                    b.Navigation("Lecturer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractMonthlyClaimSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.AcademicManager", b =>
                {
                    b.Navigation("FinalApprovedClaims");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Lecturer", b =>
                {
                    b.Navigation("MonthlyClaims");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.MonthlyClaim", b =>
                {
                    b.Navigation("ClaimItems");

                    b.Navigation("SupportingDocuments");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ProgrammeCoordinator", b =>
                {
                    b.Navigation("ApprovedClaims");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
